import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
const env = vi.hoisted(() => ({ isQuestionActive: false }))
vi.mock('@/stores/petEnv', () => ({ usePetEnvStore: () => env }))
import { isEmoji, useSpeechBubble } from './useSpeechBubble'

beforeEach(() => { vi.useFakeTimers(); env.isQuestionActive = false })
afterEach(() => vi.useRealTimers())
describe('speech bubble image replies', () => {
  it('finishes reading the text before showing a separate three-second image', () => {
    const b = useSpeechBubble()
    const shown = vi.fn()
    b.sayReply({ text: '好耶。', image: { src: '/emojis/v1/laopu/happy-1.jpg', label: '开心' }, onImageShown: shown }, true, true)
    expect(b.mode.value).toBe('typing')
    expect(b.text.value).toBe('好耶。')
    expect(b.emoji.value).toBe('')
    expect(shown).not.toHaveBeenCalled()
    vi.advanceTimersByTime(2884) // 3 characters: typing + original reading time
    expect(b.mode.value).toBe('typing')
    vi.advanceTimersByTime(1)
    expect(b.mode.value).toBe('emoji')
    expect(b.text.value).toBe('')
    expect(b.emojiLabel.value).toBe('开心')
    expect(shown).toHaveBeenCalledTimes(1)
    vi.advanceTimersByTime(2999)
    expect(b.visible.value).toBe(true)
    vi.advanceTimersByTime(1)
    expect(b.visible.value).toBe(false)
    b.say('仅文字', true, true)
    expect(b.emoji.value).toBe('')
    expect(b.text.value).toBe('仅文字')
    b.hide()
  })
  it('cancels the queued image without cutting short the current text or consuming image cooldown', () => {
    const b = useSpeechBubble()
    const shown = vi.fn()
    b.sayReply({ text: '好耶。', image: { src: '/assets/emoji/happy-1.jpg', label: '开心' }, onImageShown: shown }, true, true)
    vi.advanceTimersByTime(1000)
    b.cancelPendingReaction()
    expect(b.visible.value).toBe(true)
    expect(b.text.value).toBe('好耶。')
    vi.advanceTimersByTime(1885)
    expect(b.visible.value).toBe(false)
    expect(b.emoji.value).toBe('')
    expect(shown).not.toHaveBeenCalled()
  })
  it.each(['lyrics', 'notes', 'status', 'new speech', 'hide', 'new question'])('does not leak a queued image after %s', (replacement) => {
    const b = useSpeechBubble()
    const shown = vi.fn()
    b.sayReply({ text: '好耶。', image: { src: '/assets/emoji/happy-1.jpg', label: '开心' }, onImageShown: shown }, true, true)
    vi.advanceTimersByTime(500)
    if (replacement === 'lyrics') b.showLyric('歌词')
    else if (replacement === 'notes') b.showNotes()
    else if (replacement === 'status') b.showStatus('thinking')
    else if (replacement === 'new speech') b.say('新的回复', true, true)
    else if (replacement === 'new question') env.isQuestionActive = true
    else b.hide()
    vi.advanceTimersByTime(10000)
    expect(b.mode.value).not.toBe('emoji')
    expect(b.emoji.value).toBe('')
    expect(shown).not.toHaveBeenCalled()
    b.hide()
  })
  it('keeps legacy picture sentences and cancels pending images when lyrics arrive', () => {
    const b = useSpeechBubble()
    b.say('/assets/emoji/happy-1.jpg', true)
    vi.advanceTimersByTime(600)
    expect(b.mode.value).toBe('emoji')
    vi.advanceTimersByTime(3999)
    expect(b.visible.value).toBe(true)
    vi.advanceTimersByTime(1)
    expect(b.visible.value).toBe(false)
    b.say('/assets/emoji/cry.jpg', true)
    b.showLyric('歌词')
    vi.advanceTimersByTime(600)
    expect(b.mode.value).toBe('lyric')
    expect(b.emoji.value).toBe('')
    b.hide()
  })
  it('keeps the question lock and never interprets prose or external URLs as images', () => {
    const b = useSpeechBubble()
    env.isQuestionActive = true
    expect(b.sayReply({ text: '别打断提问' })).toBe(false)
    expect(b.visible.value).toBe(false)
    expect(isEmoji('谢谢，/assets/emoji/happy-1.jpg')).toBe(false)
    expect(isEmoji('https://outside.test/track.jpg')).toBe(false)
    expect(isEmoji('/assets/emoji/../secret.png')).toBe(false)
  })
})
