export { default as AvatarCore } from './AvatarCore.vue'
export { default as BackgroundLayer } from './BackgroundLayer.vue'
export { default as RegionContainer } from './RegionContainer.vue'
export { default as DesktopPet } from './DesktopPet.vue'
export { default as LoadingScreen } from './LoadingScreen.vue'
